// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  // TODO: flutterfire configure 실행 후 실제 값으로 교체
  // 현재는 kofilter-f28d8 프로젝트 기반 플레이스홀더
  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB4Nz81Ej5Ai0L6R02QfcDnF1wv4JtRfyk',
    appId: '1:442733554069:android:PLACEHOLDER_HEALTH_APP',
    messagingSenderId: '442733554069',
    projectId: 'kofilter-f28d8',
    storageBucket: 'kofilter-f28d8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCwH38YyxFHNGKsN6Whdg4QuOXD9Zic5Us',
    appId: '1:442733554069:ios:PLACEHOLDER_HEALTH_APP',
    messagingSenderId: '442733554069',
    projectId: 'kofilter-f28d8',
    storageBucket: 'kofilter-f28d8.firebasestorage.app',
    iosBundleId: 'com.rhythmicaleskimo.healthApp',
  );
}
